##DataBase Setting
#  spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
#  spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/dongwon?&characterEncoding=utf8&serverTimezone=Asia/Seoul
#  spring.datasource.hikari.username=root
#  spring.datasource.hikari.password=1010
#
##MyBatis Setting
##mybatis.type-aliases-package=com.dongwon.dearfood.contents.mapper
##mybatis.mapper-locations=mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dongwon?&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1010